name: Build and Test

# Controls when the action will run
on:
  push:
    branches:
      - fix_databricks_bundle_validate 
  pull_request:
    branches:
      - main

# Define the jobs that will run
jobs:
  build:
    # The name of the runner
    runs-on: ubuntu-latest

    # Steps for the build process
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # 
      # - name: Install Flake8
      #   run: pip install flake8

      # - name: Run Flake8
      #   run: flake8 
      #   continue-on-error: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: check
      #   run: az account show
      
      # Install dependencies (example for Python projects)
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      - name: Validate Databricks Asset Bundle
        run: |
          databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}


      - name: Deploy resources to Databricks
        run: |
          databricks bundle deploy
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
